- hosts: remotemachine
  gather_facts: no
  become: true
  remote_user: root

  tasks:
    #Loop over the files in the output directory and store them in a list
    - name: Find result files
      shell: (cd /hadoop_job/job_files/job_data/output; find . -maxdepth 1 -type f) | cut -d'/' -f2
      register: files_to_copy
  
    #Fetch all the items in that list
    - name: Fetch resultsd
      fetch:
        src: "/hadoop_job/job_files/job_data/output/{{ item }}"
        dest: /results
      with_items: "{{ files_to_copy.stdout_lines }}"