# - hosts: ec2-3-10-221-224.eu-west-2.compute.amazonaws.com
#   gather_facts: no
#   become: true
#   remote_user: ubuntu

#   tasks:
---  
    - name: Install and start docker
      include: install_docker_playbook.yml

    - name: Pull necessary images for YARN
      include: pull_images_playbook.yml
    
    - name: Start docker containers
      include: start_containers_playbook.yml

    - name: Run job
      include: run_job_playbook.yml
