# ---------------------------------------------------------------------------
# "OrdererOrgs" - Definition of organizations managing orderer nodes
# ---------------------------------------------------------------------------
OrdererOrgs:
  # ---------------------------------------------------------------------------
  # Orderer
  # ---------------------------------------------------------------------------
  - Name: Stavanger
    Domain: stavanger.no
    EnableNodeOUs: true
    Specs:
      - Hostname: orderer0
# ---------------------------------------------------------------------------
# "PeerOrgs" - Definition of organizations managing peer nodes
# ---------------------------------------------------------------------------
PeerOrgs:
  # - Name: Stavanger
  #   Domain: stavanger.no
  #   EnableNodeOUs: true
  #   Template:
  #     Count: 1
  #   Users:
  #     Count: 1
  
  - Name: Netherlands
    Domain: netherlands.nl
    EnableNodeOUs: true
    Template:
      Count: 1
    Users:
      Count: 1

  - Name: Spain
    Domain: spain.es
    EnableNodeOUs: true
    Template:
      Count: 1
    Users:
      Count: 1