---
    - name: Pull namenode image.
      docker_image:
        name: bde2020/hadoop-namenode:2.0.0-hadoop3.2.1-java8
        source: pull

    - name: Pull datanode image.
      docker_image:
        name: bde2020/hadoop-datanode:2.0.0-hadoop3.2.1-java8
        source: pull

    # - name: Pull nodemanager image.
    #   docker_image:
    #     name: bde2020/hadoop-nodemanager:2.0.0-hadoop3.2.1-java8
    #     source: pull

    # - name: Pull resourcemanager image.
    #   docker_image:
    #     name: bde2020/hadoop-resourcemanager:2.0.0-hadoop3.2.1-java8
    #     source: pull

    # - name: Pull resourcemanager image.
    #   docker_image:
    #     name: bde2020/hadoop-historyserver:2.0.0-hadoop3.2.1-java8
    #     source: pull

    - name: Pull base image.
      docker_image:
        name: bde2020/hadoop-base:2.0.0-hadoop3.2.1-java8
        source: pull

    - name: Pull submit image.
      docker_image:
        name: bde2020/hadoop-submit:2.0.0-hadoop3.2.1-java8
        source: pull