# AWS playbook
---

    - hosts: localhost
      connection: local
      gather_facts: False
    
      vars:
        region: eu-west-2
        sec_group: "{{ id }}-sec"
    
      tasks:
    
        - name: Facts
          block:
    
          - name: Get instances facts
            ec2_instance_facts:
              aws_access_key: "{{ec2_access_key}}"
              aws_secret_key: "{{ec2_secret_key}}"
              region: "{{ region }}"
            register: result
    
          - name: Instances ID
            debug:
              msg: "ID: {{ item.instance_id }} - State: {{ item.state.name }} - Public DNS: {{ item.public_dns_name }}"
            loop: "{{ result.instances }}"


        - name: Terminate instances that were previously launched
          ec2:
            aws_access_key: "{{ec2_access_key}}"
            aws_secret_key: "{{ec2_secret_key}}"
            state: 'absent'
            instance_ids: '{{ item.instance_id }}'
            region: '{{ region }}'
          loop: "{{ result.instances }}"
  
          tags: always